#pragma once
#define DEVICE_NAME "smart_shelf_tag"

// Auto-generated by PinPilot
#define EPAPER_SPI_2P13_SCLK 4
#define EPAPER_SPI_2P13_MOSI 5
#define BME280_I2C_SCL 10
#define BME280_I2C_SDA 6
#define EPAPER_SPI_2P13_CS 3
#define EPAPER_SPI_2P13_DC 7
#define EPAPER_SPI_2P13_RST 20
#define EPAPER_SPI_2P13_BUSY 21
