from __future__ import annotations
from pathlib import Path
import json
import shutil


def _sanitize_macro(name: str) -> str:
    # "epaper_spi_2p13.CS" -> "EPAPER_SPI_2P13_CS"
    return name.upper().replace(".", "_").replace("-", "_")


def write_pinmap_h(pinmap_payload: dict, out_include_dir: Path, device_name: str) -> None:
    """
    Creates include/pinmap.h from pinmap["assignments"].
    pinmap_payload is the full API payload, containing payload["pinmap"]["assignments"].
    """
    out_include_dir.mkdir(parents=True, exist_ok=True)
    assignments = pinmap_payload["pinmap"]["assignments"]

    lines = []
    lines.append("#pragma once\n")
    lines.append(f'#define DEVICE_NAME "{device_name}"\n\n')
    lines.append("// Auto-generated by PinPilot\n")
    for k, gpio in assignments.items():
        macro = _sanitize_macro(k)
        lines.append(f"#define {macro} {int(gpio)}\n")

    (out_include_dir / "pinmap.h").write_text("".join(lines), encoding="utf-8")


def generate_platformio_project(
    *,
    templates_dir: Path,
    project_dir: Path,
    pinmap_payload: dict,
    device_name: str,
) -> Path:
    """
    Copies firmware template into project_dir/firmware and writes include/pinmap.h.
    Returns firmware path.
    """
    firmware_template = templates_dir / "firmware"
    firmware_out = project_dir / "firmware"

    if firmware_out.exists():
        shutil.rmtree(firmware_out)

    shutil.copytree(firmware_template, firmware_out)

    # write pinmap.h
    include_dir = firmware_out / "include"
    write_pinmap_h(pinmap_payload, include_dir, device_name)

    return firmware_out
